<?php

function notify($to,$data){

    $api_key="AAAAyYy7RXA:APA91bGliUwgs8hQeQy-Z8YkO90KFmHBVrjOPkqaMNFMyI2CvRwfX-bJQg13wPayS7mammqF4qt6Z_lsGm3sSwpeVhOpvnqmMnRpf4g0BzZFLQ4GBkyTcZaGInt4yxYXajxYn1DasT74";
    $url="https://fcm.googleapis.com/fcm/send";
    $fields=json_encode(array('to'=>$to,'notification'=>$data));

    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, ($fields));

    $headers = array();
    $headers[] = 'Authorization: key ='.$api_key;
    $headers[] = 'Content-Type: application/json';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);
}

$to= $_POST['device'];
$data=array(
    'title'      => 'Semangat Pagi',
    'body'       => $_POST['body'],
    'sound'      => 'notification_sound_wav',
    'channel_id' => '101'
);

notify($to,$data);
echo "Notification Sent";

?>